# Generated by Django 2.1 on 2018-09-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0013_auto_20180910_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Design', models.TextField()),
            ],
        ),
    ]
