# Generated by Django 2.0.6 on 2018-09-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0016_auto_20180927_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='livecanvas',
            name='Type',
            field=models.TextField(default='draw'),
        ),
    ]
