# Generated by Django 2.1.1 on 2018-10-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0017_livecanvas_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts',
            name='Safety',
        ),
        migrations.RemoveField(
            model_name='parts',
            name='Scores',
        ),
    ]
