# Generated by Django 2.1.1 on 2018-10-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0018_auto_20181001_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='Chassis',
            field=models.CharField(default='Pichia pastoris ', max_length=100),
        ),
    ]
