# Generated by Django 2.1 on 2018-08-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='Role',
            field=models.CharField(default='sequenceFeature', max_length=20),
        ),
    ]
