# Generated by Django 2.1 on 2018-08-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_parts_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', editable=False, max_length=32, unique=True),
        ),
    ]
