# Generated by Django 2.1 on 2018-09-03 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20180903_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='Chassis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.Chassis'),
        ),
    ]
