# Generated by Django 2.1 on 2018-09-06 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_auto_20180903_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuit',
            name='Author',
        ),
        migrations.AddField(
            model_name='circuit',
            name='Editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circuit_requests_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circuit',
            name='Master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circuit_requests_master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circuit',
            name='Update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
