# Generated by Django 2.1 on 2018-09-06 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_auto_20180906_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuit',
            name='Master',
        ),
        migrations.AddField(
            model_name='circuit',
            name='Author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circuit_requests_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
