# Generated by Django 2.1 on 2018-08-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_auto_20180819_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='IsPublic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parts',
            name='Username',
            field=models.CharField(default='Unknown', max_length=32),
        ),
    ]
