# Generated by Django 2.1 on 2018-09-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_authorities'),
        ('design', '0006_auto_20180906_0835'),
    ]

    operations = [
    ]
