# Generated by Django 2.1 on 2018-08-28 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_auto_20180819_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chassis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='circuit',
            name='Chassis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='design.Chassis'),
        ),
    ]
