# Generated by Django 2.1 on 2018-08-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0009_auto_20180831_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='chassis',
            name='data',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chassis',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
