# Generated by Django 2.1 on 2018-09-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0010_auto_20180908_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='Comment',
            field=models.CharField(default='None', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='works',
            name='DefaultImg',
            field=models.URLField(default='static/img/Team_img/none.jpg'),
        ),
        migrations.AlterField(
            model_name='works',
            name='logo',
            field=models.URLField(default='static/img/Team_img/none.jpg'),
        ),
    ]
