# Generated by Django 2.0.6 on 2018-09-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0015_auto_20180920_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveCanvas',
            fields=[
                ('Design', models.TextField()),
                ('Path', models.TextField()),
                ('Order', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='realtimedesign',
            name='Circuit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='design.Circuit'),
        ),
        migrations.AlterField(
            model_name='works',
            name='DefaultImg',
            field=models.URLField(default='static\\img\\Team_img\\none.jpg'),
        ),
        migrations.AlterField(
            model_name='works',
            name='logo',
            field=models.URLField(default='static\\img\\Team_img\\none.jpg'),
        ),
    ]
